#!/bin/bash -x

# Create new environment from scratch:
# First try ept11 == env_pytorch_311
# else:
# conda create -n env_pw_311 python=3.11
# conda activate env_pw_311
# alias epw11 'conda activate env_pw_311'

# Install core packages
conda install pytorch torchvision torchaudio -c pytorch
conda install numpy protobuf tensorflow -c conda-forge

# Additional packages if needed
# conda install scipy

python demo.py --mode train
python demo.py --mode train --resume snapshots/checkpoint_epoch_5.pt
python demo.py --mode generate
