#!/bin/bash -x

# Create new environment from scratch:

conda create -n env_pytorch_311 python=3.11
conda activate env_pytorch_311

# Install core packages
conda install pytorch torchvision torchaudio -c pytorch
conda install numpy protobuf tensorflow -c conda-forge

# Additional packages if needed
# conda install scipy

python demo.py --mode train
python demo.py --mode train --resume snapshots/checkpoint_epoch_5.pt
python demo.py --mode generate
