#!/bin/bash -x

# Python 3.12 is working as of 2025-03-04:
conda init
conda activate env_pytorch_312
# Previously Python 3.12 would not work:
# Create new environment from scratch:
# First try ept11 == env_pytorch_311
# else:
# conda create -n env_pw_311 python=3.11
# conda activate env_pw_311
# alias epw11 'conda activate env_pw_311'
#
# Install core packages
# conda install pytorch torchvision torchaudio -c pytorch
# conda install numpy protobuf tensorflow -c conda-forge
#
# Additional packages if needed
# conda install scipy

python demo.py --mode train
python demo.py --mode train --resume snapshots/best_model.pt
python demo.py --mode generate
